
#General settings
[gardentools]

	[gardentools.cultivator]
		#Range of cultivator item
		#Range: 2 ~ 32
		range = 9
		#Moisture level set by cultivator
		#Range: 0 ~ 7
		moisture = 7

	[gardentools.planter]
		#Range of planter item
		#Range: 2 ~ 32
		range = 9

	[gardentools.irrigator]
		#Watering radius of irrigation block
		#Range: 1 ~ 16
		radius = 4

