

mod_id=gardentools
curse_slug=garden-tools
curse_id=351990
mod_version=1.2.0
mod_name=gardentools
mod_group_id=com.lothrazar.gardentools
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=gardening-tools

flib_version=0.2.0
flib_file=8117455


